FROM node:18.0-alpine

RUN mkdir -p /project/react-app/node_modules && chown -R node:node /project/react-app

WORKDIR /project/react-app

COPY . .

COPY --chown=node:node . .

# 'root' is only for dev mode, must be replaced with 'node' for production
USER root

RUN yarn

EXPOSE 3000

CMD [ "yarn", "start" ]
